// Build-time image-format resolver (docs/assets.md).
// Scans public/images and records, for each image "base" path (no extension),
// the best real file present — preferring photographic rasters (webp/avif/jpg/
// png) over the auto-generated .svg placeholder. Writes src/content/
// image-manifest.js (a plain ESM module, so it imports cleanly in BOTH the Next
// bundle and Node scripts without JSON import attributes).
//
// This is what lets the whole site "take svg AND webp": drop a real file at any
// declared path, re-run (prebuild/predev do this automatically), and the code
// serves it — otherwise it falls back to the .svg placeholder.
//
// Run via: `npm run images` (also chained into prebuild / predev / placeholders).
import { readdirSync, statSync, writeFileSync, mkdirSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const PUBLIC = path.join(ROOT, 'public');
const IMAGES_DIR = path.join(PUBLIC, 'images');
const OUT = path.join(ROOT, 'src', 'content', 'image-manifest.js');

// Lower index = higher priority. Real formats win over the svg placeholder.
const PRIORITY = ['webp', 'avif', 'jpg', 'jpeg', 'png', 'svg'];
const rank = (ext) => {
  const i = PRIORITY.indexOf(ext);
  return i === -1 ? Number.POSITIVE_INFINITY : i;
};

/** base ('/images/home/hero') -> best extension ('webp') */
const map = {};

function walk(dir) {
  for (const name of readdirSync(dir)) {
    const abs = path.join(dir, name);
    if (statSync(abs).isDirectory()) {
      walk(abs);
      continue;
    }
    const ext = path.extname(name).slice(1).toLowerCase();
    if (!PRIORITY.includes(ext)) continue;
    const relFromPublic = path.relative(PUBLIC, abs).split(path.sep).join('/');
    const base = '/' + relFromPublic.replace(/\.[^.]+$/, '');
    if (!(base in map) || rank(ext) < rank(map[base])) map[base] = ext;
  }
}

try {
  walk(IMAGES_DIR);
} catch (err) {
  if (err.code !== 'ENOENT') throw err; // no images dir yet → empty manifest
}

const sortedKeys = Object.keys(map).sort();
const body = JSON.stringify(map, sortedKeys, 2);
const file = `// AUTO-GENERATED by scripts/resolve-images.mjs — do not edit by hand.
// Maps each image base path to the best real file present (webp/jpg/png win
// over the .svg placeholder). Re-run \`npm run images\` after adding assets.
export default ${body};
`;

mkdirSync(path.dirname(OUT), { recursive: true });
writeFileSync(OUT, file, 'utf8');
console.log(`image-manifest: resolved ${sortedKeys.length} images → ${path.relative(ROOT, OUT)}`);
